server:
    port: [port]

management:
    address: [ip]
    port: 39100

logging:
    level:
        com.linecorp.sample: DEBUG

linecorp:
    platform:
        channel:
            channelId: xxx
            channelSecret: xxx
            callbackUrl: http://[ip]:[port]/auth